services:
  mongo1:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro # 映射 keyFile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]

  mongo2:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo2-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro # 映射 keyFile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]

  mongo3:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo3-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro # 映射 keyFile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
